package org.renap.orm.activosorm;
// Generated 14/09/2015 07:12:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivoTecnologia generated by hbm2java
 */
@Entity
@Table(name="activo_tecnologia"
)
public class ActivoTecnologia  implements java.io.Serializable {


     private Integer id;
     private String nombre_mac;
     private String ip;
     private String marca;
     private String user;
     private Date fecha;

    public ActivoTecnologia() {
    }

    public ActivoTecnologia(String nombreMac, String ip, String marca, String user, Date fecha) {
       this.nombre_mac = nombreMac;
       this.ip = ip;
       this.marca = marca;
       this.user = user;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre_mac", length=200)
    public String getNombre_mac() {
        return this.nombre_mac;
    }
    
    public void setNombre_mac(String nombreMac) {
        this.nombre_mac = nombreMac;
    }

    
    @Column(name="ip", length=45)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    @Column(name="marca", length=45)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="user", length=45)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


